#------------------------------------------------------------------------------
# This file must not contain any IP address, please use ~/.ssh/config to map
# siconia host to real hostname (dns) or ip address.
#
# For instance : ~/.ssh/config
#
# Host #   HostName localhost
#   User g565069
#   IdentityFile ~/.ssh/id_rsa  
#
# Host siconia*
#   HostName localhost
#   User g565069
#   IdentityFile ~/.ssh/id_rsa
#
#------------------------------------------------------------------------------
# Keep entries ordered in an alphabetical order

#------------------------------------------------
#               Apache tomcat hosts
#------------------------------------------------

apache_tomcat:
   hosts:
     siconia-apache-tomcat-01:
