
# tasks file to join the domain


- name: "Installing Required packages"
  import_tasks: install.yml

- name: "Discover the domain name"
  import_tasks: discover.yml

- name: "Join the domain name"
  import_tasks: join.yml

- name: Edit SSSD configuration file
  import_tasks: sssd_config.yml
  notify:
  - restart sssd

- name: To permit a user access via SSH and console and Admin to sudoers
  import_tasks: permit.yml
  notify:
  - restart sssd

- name: Edit SSH configuration file
  import_tasks: sshd_config.yml
  notify:
  - restart sshd
