
---

- name: Checking Domain Join status
  ansible.builtin.shell: /bin/bash -c "/usr/sbin/realm discover {{ ad_server.domain }}"
  register: ad_status
  changed_when: false
  ignore_errors: true
  no_log: True

- name: Debug the AD status
  debug:
   msg: "{{ ad_status }}"
