---

- name: Checking Domain Join status if it's existe
  ansible.builtin.shell: /bin/bash -c "/usr/sbin/realm discover {{ ad_server.domain }}"
  register: ad_status

- name: Debug the AD status
  debug:
   msg: "{{ ad_status }}"
