---


- name: Join system
  command: /bin/bash -c "echo {{ ad_server.pass }} | realm join {{ ad_server.domain }} --user={{ ad_server.user }} "
  register: join_output
  ignore_errors: yes
  no_log: True
  

- name: Display success message
  debug:
    msg: "Join successful!"
  when: join_output.rc == 0

- name: Display error message
  debug:
      msg: "Join failed or already joined"
  when: join_output.rc != 0
