---

    - name: Update the default config
      lineinfile: 
          backup: yes
          state: present
          dest: "/etc/ssh/sshd_config"
          regexp: '^PasswordAuthentication'
          line: 'PasswordAuthentication yes'
    - name: Check if sshd_config.d exist
      stat:
        path: /etc/ssh/sshd_config.d
      register: sshd_config_dir
    - name: Get list of config file
      find:
        paths: "/etc/ssh/sshd_config.d/"
        patterns: "*.conf"
      register: sshd_config
      when: sshd_config_dir.stat.exists
    - name: Override the default sshd config
      lineinfile: 
        backup: yes
        state: present
        dest: "{{ item }}"
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      with_items: "{{ sshd_config.files | map(attribute='path') | list }}"
      when: sshd_config_dir.stat.exists