---
# handlers file for ad_join

- name: restart sssd
  ansible.builtin.systemd: 
    name: sssd 
    state: restarted

- name: restart sshd
  ansible.builtin.systemd: 
    name: sshd 
    state: restarted